//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digioz.Portal.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureAlbum
    {
        public PictureAlbum()
        {
            this.Pictures = new HashSet<Picture>();
        }
    
        public long ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<bool> Visible { get; set; }
    
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
