//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digioz.Portal.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public long ID { get; set; }
        public string UserID { get; set; }
        public Nullable<long> AlbumID { get; set; }
        public string Filename { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual MembershipUser AspNetUser { get; set; }
        public virtual VideoAlbum VideoAlbum { get; set; }
    }
}
