//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digioz.Portal.Web.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Config
    {
        public int ID { get; set; }
        [Required]
        [DisplayName("Key")]
        public string ConfigKey { get; set; }
        [Required]
        [DisplayName("Value")]
        public string ConfigValue { get; set; }
    }
}
