//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digioz.Portal.Web.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Announcements = new HashSet<Announcement>();
            this.AspNetUserClaims = new HashSet<UserClaim>();
            this.AspNetUserLogins = new HashSet<UserLogin>();
            this.Menus = new HashSet<Menu>();
            this.Pages = new HashSet<Page>();
            this.AspNetRoles = new HashSet<Role>();
            this.Profiles = new HashSet<Profile>();
            this.Pictures = new HashSet<Picture>();
            this.Videos = new HashSet<Video>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string Discriminator { get; set; }
    
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<UserClaim> AspNetUserClaims { get; set; }
        public virtual ICollection<UserLogin> AspNetUserLogins { get; set; }
        public virtual ICollection<Menu> Menus { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<Role> AspNetRoles { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
